spring.application.name=SeatSync
server.port=8080
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.devtools.restart.enabled=true
spring.config.import=optional:file:.env[.properties]

# --- Persistence (dev) ---
spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:h2:file:./seatSync-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}}
spring.datasource.driverClassName=${JDBC_DATABASE_DRIVER:${DATABASE_DRIVER:org.h2.Driver}}
spring.datasource.username=${JDBC_DATABASE_USERNAME:${DATABASE_USERNAME:sa}}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:${DATABASE_PASSWORD:}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
